### ISSUE TITLE
Change favicon?

### ISSUE THREAD

**Issue by WorldsEndless** [Vimux/Binario#1]
Is there a way for me to change the favicon from the default icons without editing the theme itself?

**Comment by Vimux** [comment]
You can "replace" default fav icons (`icons/16.png` & `icons/32.png`) with your own.

Place your icons with the same name (`16.png` & `32.png`) in `static/icons` folder within your Hugo website.

**Comment by WorldsEndless** [comment]
Thank you. Is there a reason it doesn't use the Hugo  assumption that you'll have a favicon.ico in your /static dir?

**Comment by Vimux** [comment]
> Is there a reason it doesn't use the Hugo assumption that you'll have a favicon.ico in your /static dir?

There is no "the Hugo assumption". Hugo moves files from `static` dir into the site root folder when the site generated. That's all. In most cases, browsers will find your favicon.ico file in the root if no favicon links in HTML file.

I don't plan to use the favicon.ico by default in Binario. For my needs, it is easier to maintain .png as favicons.
