### ISSUE TITLE
bad language when multilingual 

### ISSUE THREAD

**Issue by Sigerking** [Vimux/Binario#2]
hello, hi !!! Binario is fun and cool !

I tryed to configure multilingual mode in binario. I order to that :
- created folder for each language.   
- config i18n in site root and created file fr.yaml
- copy about in 2 folders french and english
- translated the content of about file in french folder
-modified config file for french with weight 1 (right under)
````
baseURL = "https://example.com/"
title = "Coh@bit - Fablab"

languageCode = "fr"

paginate = 10
theme = "binario"

[Params]
  description = "le Fablab de l'université de Bordeaux"
  columns = 2
  mainSections = ["post"]
  dateFormat = "January 02, 2006"

DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
[languages]
  [languages.fr]
    contentDir = "content/french"
    languageName = "Français"
    weight = 1
    
  [languages.en]
    contentDir = "content/english"
    languageName = "English"
    weight = 2`
```
Then I run hugo server, no error returned, but Site still use english file contents. Did I missed something?

**Comment by Vimux** [comment]
Hi, @Sigerking 

Please upload test repository with a problem, if you want to get help. Thank you.

**Comment by Sigerking** [comment]
Hi, @Vimux 
Thank you very much for your quick reply.
here link of my test repository 👎 
[https://github.com/Sigerking/testbinario/invitations]
I hope to get help me.

**Comment by Sigerking** [comment]
Hi, @Vimux 
It's OK !!!!! I must write localhost:1313/fr for french version.

**Comment by Vimux** [comment]
OK. I close the issue.
