### ISSUE TITLE
Table of Content not working

### ISSUE THREAD

**Issue by J-Siu** [Vimux/Binario#21]
If I enable toc, the "Table of Contents" will show but empty if expended.

**Comment by Vimux** [comment]
Hello,

Could you please follow [reporting bugs section](https://github.com/Vimux/Binario/blob/master/CONTRIBUTING.md#reporting-bugs)?

**Comment by J-Siu** [comment]
hugo version:
Hugo Static Site Generator v0.60.1/extended darwin/amd64 BuildDate: unknown

OS: MacOS Catalina 10.15.2

Theme update to latest with: 
git clone https://github.com/Vimux/Binario.git
No modification.

Enabled toc in config.toml:

```toml
[Params]
  ...
  toc = true
  tocOpen = true
```

No error from hugo command.

Screenshot example, url: https://johnsiu.com/blog/ubuntu-cmd/
![Screen Shot 2019-12-11 at 12 32 03 PM](https://user-images.githubusercontent.com/3171920/70645874-cd260a00-1c13-11ea-9356-7e64a880a26e.png)

**Comment by Vimux** [comment]
It's Hugo v0.60.0 (and later) related thing. Your example contains only #### (h4) headings inside. As a result, empty Table of contents.

---

I think you should have read the changelog before you updated Hugo. Otherwise, you will encounter such errors periodically.

**Comment by J-Siu** [comment]
Thank you! And sorry about that, I should have check the release notes. It is my bad. I will close the issue.
