### ISSUE TITLE
hugo v0.61.0 ToC does not nest/indent correctly

### ISSUE THREAD

**Issue by J-Siu** [Vimux/Binario#22]
Original reported to https://github.com/gohugoio/hugo/issues/6613

hugo version:
Hugo Static Site Generator v0.60.1/extended darwin/amd64 BuildDate: unknown

OS: MacOS Catalina 10.15.2

Theme update to latest with:
git clone https://github.com/Vimux/Binario.git
No modification.

Live URL: https://johnsiu.com/blog/k8s-installation/
Raw md: https://raw.githubusercontent.com/J-Siu/johnsiu.com/master/content/blog/k8s-installation.md
Theme: https://github.com/Vimux/Binario (latest pull master)

I added following in my config.toml:

```toml
[markup]
  [markup.tableOfContents]
    endLevel = 10
    startLevel = 3
````

The ToC does not nest/indent correctly:
![Screen Shot 2019-12-12 at 2 38 50 AM](https://user-images.githubusercontent.com/3171920/70692423-50ce0e00-1c89-11ea-9e7f-09822247dd71.png)

The 3 lines in red rectangle are level 4 and should be indented.

PS: I tried using the default(removing the markup section) and reduce all headers by 1 level but result is the same.

**Comment by Vimux** [comment]
> The ToC does not nest/indent correctly:

Yes, because `{{ .TableOfContents }}` output format has changed in Hugo 0.60.0 and later. I don't know how to fix this (without dirty workarounds of course) and don't break all previous versions (0.54.0-0.59.0) without bumping. There is no CSS classes or something else that I could use to determine current render engine which is used.

If you have ideas on how to fix this without bumping the minimum version, you can always open a new PR.

**Comment by J-Siu** [comment]
This was driving me nuts but I think I am getting to the root cause and doesn't seems to be a theme issue.

I open https://github.com/gohugoio/hugo/issues/6623 with hugo. Let see if they kick me back again this time.

PS: Is `tocOpen = true` not working?

**Comment by J-Siu** [comment]
6623 got closed. But I finally did a test with another theme(yinyang), it actually work correctly with following in config:

```toml
[markup]
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 3
```

So it seems to circle back to your theme😓

Following is my test:

In blog directory:

```sh
git clone https://github.com/joway/hugo-theme-yinyang.git themes/yinyang
```

In `themes/yinyang/layouts/_default/single.html` Ln 35 add:

```md
					{{ .TableOfContents }}
```

Switch theme to yinyang in config (I just use the one same one for bianario) and the toc is correct.

My whole blog repo is https://github.com/J-Siu/johnsiu.com, you can find my current config there. There is a johnsiu.com/content/page/toc_test.md I use to test the toc.

---

hugo >=0.60, regarding which md engine is being use, in https://gohugo.io/getting-started/configuration-markup :

Following will set the md engine to the old one (<0.60).
```toml
[markup]
  defaultMarkdownHandler = "blackfriday"
```

If `defaultMarkdownHandler` is not set, then hugo will default to goldmark.

But that only apply to hugo >=0.60, not sure if there is other parameter you can use to detect blackfriday in <0.60.
