### ISSUE TITLE
Is it possible to have a hugo theme rendering to a subpath ?

### ISSUE THREAD

**Issue by sokoow** [Vimux/Binario#25]
Hey :) Very nice theme! Well done :D

I am wondering whether it is possible to use a theme on a subpath, so:

1. I got hugo with my custom layouts rendering my / contents
2. I .. somehow include your theme, and make it render to /blog tree on my site

Do you know whether this is possible at all ?

**Comment by Vimux** [comment]
You can always ask such questions on the [Hugo community forum](https://discourse.gohugo.io/).
