### ISSUE TITLE
Configure sub-reddit for share

### ISSUE THREAD

**Issue by Marthym** [Vimux/Binario#27]
Maybe it can be usefull to allow configuring sub-reddit for share on reddit button ?

**Comment by Vimux** [comment]
Hello,

Use case?

**Comment by Marthym** [comment]
By default the button open a dialog with no community selected. 

If it is possible to add default community, for a subject oriented blog, it is a way to centralize the votes and comments

**Comment by Vimux** [comment]
Yeah, it makes sense in such cases, but it's not a general thing, I think. So, If you want something like this for your site, you need to create custom share partial.
