### ISSUE TITLE
How to Change the Page Order in the Navigation Menu

### ISSUE THREAD

**Issue by easybeau** [Vimux/Binario#3]
Hi,

Thanks for this nice theme!

I would like to change the order of the elements of the menu. How can I do that?

Thanks for your answer.

Best regards

**Comment by Vimux** [comment]
Hello.

Yes, you can change menu items order with `weight` variable. 

`config.toml`:
```
[menu]
  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
```

Reference:
[Site Config menus](https://gohugo.io/templates/menu-templates/#site-config-menus)
[Menu Entry Variables](https://gohugo.io/variables/menus/#menu-entry-variables)

**Comment by ttbek** [comment]
@easybeau 
Here is another example in use: 
```
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -999
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = -998
  [[menu.main]]
    identifier = "tutorials"
    name = "Tutorials"
    url = "/tutorials/"
    weight = -997
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = -1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = -2
  [[menu.footer]]
    identifier = "Legal"
    name = "Legal"
    url = "/legal/"
    weight = -999
```
You can see the site here: https://kunji.entrydns.org/

Note that you can also order the footer menu of this theme this way (though I have only one entry in the footer menu for now).

**Comment by easybeau** [comment]
Thank you

**Comment by Vimux** [comment]
@easybeau 

Problem solved? If so, please, close the issue.
