### ISSUE TITLE
theme set in config is wrong

### ISSUE THREAD

**Issue by Ayushnita** [Vimux/Binario#32]
In config file theme set is "binario" but it require to be "Binario"

**Comment by Ayushnita** [comment]
Found this issue happen when you did not provide theme/binario folder and cd into themes and use git clone <URL> .

**Comment by Vimux** [comment]
I'm pretty sure, making that assumption is not right. I don't see any reproducing steps or demo project link. If you think that the bug exists, you should follow our [CONTRIBUTING → Reporting bugs](https://github.com/Vimux/Binario/blob/master/CONTRIBUTING.md#reporting-bugs) guide.
