### ISSUE TITLE
Couple of questions concerning tags/archives/posts 

### ISSUE THREAD

**Issue by morfikov** [Vimux/Binario#35]
Is there a way to make the first paragraph of an article to be in the post summary?
Is it possible to set different column numbers for tags/categories and post view?
Is there something like archive page, where all post names are listed and grouped by year/month?
Is there a tag cloud?

**Comment by Vimux** [comment]
1. Yes. https://gohugo.io/content-management/summaries/#summary-splitting-options
2. [?] You can customize `column` param via front matter for list-like pages (including tags/categories, entries lists, etc) only.
3. No.
4. No.

---

As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes any questions like "how to do this or that", "everything is broken, help me" and so on. I don't provide tech support, so I'll close this. I hope you understand.
