### ISSUE TITLE
Only "Posts" is shown on front page

### ISSUE THREAD

**Issue by zartmann** [Vimux/Binario#36]
After upgrading to newest hugo server, it looks like index.html isn't build properly. It just shows "Posts" and not the list/index of my posts.

![Screenshot 2020-09-06 at 10 47 10](https://user-images.githubusercontent.com/49228094/92321944-85130700-f02e-11ea-9cb7-21b90efa45c4.jpg)

config.toml hasn't been changed. And when I click on the "Posts" link the list of posts look like this:

![Screenshot 2020-09-06 at 10 50 28](https://user-images.githubusercontent.com/49228094/92321988-cacfcf80-f02e-11ea-9574-a0f107c8a222.jpg)

Also, regular HTML links do not show as links - only the text is shown.

My public version still looks OK: zartmann.dk

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes reports like "how to do this or that", "everything is broken, help me", "I changed something and now it doesn't work", and so on. **The issue tracker is the preferred channel for bug reports and feature requests which comply with our contributing rules**, nothing more. I do not provide personal tech support.

**Closed and marked as invalid.**
