### ISSUE TITLE
A missing slash after category name in the URL

### ISSUE THREAD

**Issue by morfikov** [Vimux/Binario#37]
I noticed that google search console shows me some `Page with redirect` entries and all of them point to urls that can be accessed from the post list. So for instance there's

`https://morfikov.github.io/categories/linux `

and it should be 

`https://morfikov.github.io/categories/linux/`

This can be fixed by (I think) adding the missing slash in ` 'themes/binario/layouts/partials/entry/meta/categories.html'` in the 5th line:

`<a class="meta-categories__link" href="{{ "categories/" | relLangURL }}{{ . | urlize | lower }}" rel="category">`

vs.

`<a class="meta-categories__link" href="{{ "categories/" | relLangURL }}{{ . | urlize | lower }}/" rel="category">`

**Comment by Vimux** [comment]
@morfikov Could you please make a PR?

**Comment by morfikov** [comment]
Done.
