### ISSUE TITLE
How to format post?

### ISSUE THREAD

**Issue by davisi3** [Vimux/Binario#42]
Hi! I'm very new to html. I installed hugo and Binario few hours ago. I'm confused about formating my post. For example I want heading 1 as shown in this https://binario.netlify.app/post/basic-elements/ so I assumed I edit my-post.md like 
`<h1>Test<h1>` but it didn't work. Need some guidance.

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes reports like "how to do this or that", "everything is broken, help me", "I changed something and now it doesn't work", and so on. **The issue tracker is the preferred channel for bug reports and feature requests which comply with our contributing rules**, nothing more. I do not provide personal tech support.

**Closed and marked as invalid.**
