### ISSUE TITLE
Rmd post does not work 

### ISSUE THREAD

**Issue by ogansser** [Vimux/Binario#43]
Hi, I tried you theme today. The Rmd post does not work like the other md posts. bg color is white and UTF-8 also does not work. Seems that the HTML head is not the same than with md. 

Maybe this has something to go with blogdown 1.2. 

In the RStudio viewer everything seems well, but if I transfer the public folder to my webspace, the bug comes up.

**Comment by Vimux** [comment]
Hello,

I’m not a magician, I don’t know how to read people's minds. Any bug report must match the template from contributing guide. Or it's just message about everything and nothing.

https://github.com/Vimux/Binario/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by ogansser** [comment]
OK, I understand. It is impossible to write an error because in RStudio
there is no error. I try to build a new webspace later today. I think this
is a blogdown problem and has nothing to do with your theme.


Am Fr., 9. Apr. 2021 um 16:51 Uhr schrieb Vimux ***@***.***>:

**Comment by Vimux** [comment]
Closing as missing information.
