### ISSUE TITLE
Support for other comment system than Disqus

### ISSUE THREAD

**Issue by morfikov** [Vimux/Binario#44]
A few weeks ago, I received an email from Disqus saying the following:

> Hi there, 
> 
> Thanks for using Disqus! Your site was recently approved for ads, but we noticed that you don’t currently having any campaigns running. If you’d prefer a non-ads supported plan, you can choose between either of our ads-free plans here: 
> 
>     Plus - $12/month or $11/month with our yearly discount 
>     Pro - $115/month or $105/month with our yearly discount 
> 
> browse plans
> 
> Each of these plans comes with an ads-free version of Disqus and our Pro plan offers a variety of additional engagement features. You can review these options from your Subscription and Billing page. 
> 
> Thank you, 

Basically if you're not going to pay them, there's no way to use Disqus without serving intrusive adds in the comments section. I've always been having an adds free blog, and I wanted it to stay in this way. Currently I had to disable comments on my blog, and look for some Disqus alternative, but the Binario theme currently doesn't support any other comment system.

I wanted to ask whether are there any plans to make such support?

**Comment by Vimux** [comment]
No. You can always add your favourite comment system (override`comments.html` partial) by yourself.

**Comment by bugok** [comment]
A suggestion: I've tried https://utteranc.es/, and it works pretty well for me. 
It's being supported by other popular themes ([hugo-coder](https://github.com/luizdepra/hugo-coder) and [loveit](https://github.com/dillonzq/LoveIt)

Personally, I moved to my personal fork of Binario (which I really like to use) so I could use that. For reference:
- My Binario fork: https://github.com/bugok/Binario (the implementation of utterances is hard-coded, but works)
- My blog repo: https://github.com/bugok/blog
- Live blog on github.io: https://bugok.github.io/blog/

@Vimux : If you think you'd accept a PR adding support for utterances, I'd be happy to create it and send it. My motivation for this is to keep using Binario while not maintaining a personal fork.

In any case, thanks for creating and maintaining Binario.

**Comment by morfikov** [comment]
Interesting...
