### ISSUE TITLE
I want to display a specific image in the tabs.

### ISSUE THREAD

**Issue by SenlinOS** [Vimux/Binario#56]
Hi:
1. for example, I wrote in blog.md: tags: ["bysa", "Ubuntu"], "bysa" will be represented by image.

2. When I use "byncnd", the image will become cc-by-nc-nd's image. <br />(Display different images according to different Tab's text.)

Thank you.

![img](https://z3.ax1x.com/2021/10/08/5CrQr4.png)

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes reports like "how to do this or that", "everything is broken, help me", "I changed something and now it doesn't work", and so on. **The issue tracker is the preferred channel for bug reports and feature requests which comply with our contributing rules**, nothing more. I do not provide personal tech support.

**Closed and marked as invalid.**
