### ISSUE TITLE
Height of post excerpt

### ISSUE THREAD

**Issue by SenlinOS** [Vimux/Binario#6]
How can the height of the post excerpt be smaller and the same height?
Thank you~

**Comment by Vimux** [comment]
Hello.

Can you explain this in other words? I don't understand your question. Did you mean summary length or what?

**Comment by SenlinOS** [comment]
Re: @Vimux  I want to have less text for each Post-Preview and the height of each Post-Preview is the same.
![img](https://s2.ax1x.com/2019/06/14/V5HitS.jpg)

**Comment by Vimux** [comment]
>  I want to have less text...

Use `<!--more-->` divider in your content files or `summaryLength` param in your site config. See reference: [Summary Splitting Options](https://gohugo.io/content-management/summaries/#summary-splitting-options).

**Comment by SenlinOS** [comment]
> See reference: Summary Splitting Options.

Success ~
add `hasCJKLanguage = true` in config.toml
