### ISSUE TITLE
how to add the goatcounter analytics

### ISSUE THREAD

**Issue by KitsuneSemCalda** [Vimux/Binario#69]
I would like to add this open source analytics to my blog, but it doesn't identify the analytics,

**Comment by Vimux** [comment]
**I do not provide free personal technical support.** 

This includes any reports like “how to do this or that”; “everything broken, help me”; “I changed something, it doesn't work anymore”; “It's not a personal issue, I just want to ask how X or Y works”; “I forked your repository, then something broken, fix this immediately” and so on. **The issue tracker is the preferred channel for bug reports, feature requests, and discussions that comply with our contributing rules**, nothing more.

**Closed and marked as invalid.**
