### ISSUE TITLE
Time in dateFormat does not render correctly

### ISSUE THREAD

**Issue by woolwood** [Vimux/Binario#7]
As per https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
If I include `dateFormat = "January 02, 2006 13:00" ` in `config.toml`, and `2019-06-23T10:33:31+02:00` in my post's front matter, I expect to see `June 26, 2019 10:33` in the resulting html but the result is `June 26, 2019 69:00`.

Is this a bug in `layouts/partials/post_meta/date.html` or am I misunderstanding something?

**Comment by Vimux** [comment]
> Is this a bug or am I misunderstanding something?

Your DateTime snippet in config file contains a mistake (`13:00`), so it gives an incorrect time format in the result. [Hugo Date and Time Templating Reference](https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference) contains all the necessary information and examples.

**Comment by woolwood** [comment]
Oh, right, I though it would take the general format. Thank you for
pointing that out.
