### ISSUE TITLE
Meta Description is not loaded

### ISSUE THREAD

**Issue by KitsuneSemCalda** [Vimux/Binario#70]
I have add the description params in my config.toml and sended to my blog, but the google chrome lighthouse acuse my blog with seo (89) with message:

Document does not have a meta descriptionDescription text is empty.
Meta descriptions may be included in search results to concisely summarize page content. Learn more.

**Comment by Vimux** [comment]
Could you please follow our contributing guidelines for [reporting bugs](https://github.com/Vimux/Binario/blob/master/CONTRIBUTING.md#reporting-bugs)? Otherwise, I will close your issue.
