### ISSUE TITLE
Question: Is possible to create a "masonry" style in the home page?

### ISSUE THREAD

**Issue by amper87** [Vimux/Binario#75]
Hello. Just discovered hugo and binario theme is the best way to write a great website for a great chess club (Amateur Chess Club Lupiae 1970 from Lecce, Italy!!! .... little advertising!!!!! :D) Me and my friends are asking ourselves if it s possible what we ask in the title... In order to have a card very wide (e.g. with a photo attached) and then to not have the adjacent cards , in which just two lines are written, taking the height of the bigger card. Thanks and we apologize if this place was not the best to make a question like that. 

Andrea

**Comment by Vimux** [comment]
Binario doesn't have anything like that. However, there is a unique class (.kind-home), which means you can add additional styles and logic for the homepage. Nothing is impossible.

P.S. Yep, it's not the place to ask such questions.

**Comment by amper87** [comment]
Tank you for the answer (and for the patience) precious suggestions thank you
