### ISSUE TITLE
Does binario support multi languages ?

### ISSUE THREAD

**Issue by mangometer** [Vimux/Binario#80]
Hello there does this project support multi languages, saw the folder but no description in the intro and nothing in the demo like a language switch. Thanks

**Comment by Vimux** [comment]
> Does binario support multi languages ?

Yes.

> Hello there does this project support multi languages, saw the folder but no description in the intro and nothing in the demo like a language switch. Thanks

I don't see why it shouldn't work. But if you're expecting more examples from us (Hugo's documentation covers everything in this area), or a language switcher (menus solve the problem in most cases), you're probably looking in the wrong direction.
